trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AADAZDEVOPSDEV01'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az deployment sub create `
        --location 'australiaeast' `
        --template-file ./main.bicep `
        --parameters department='ictb' `
          location= 'australiaeast' `
          environment='poc' `
          application='test' 
